### ISSUE TITLE
メールアドレス登録・変更時の認証メールが届かない

### ISSUE THREAD

**Issue by tkc-alien** [tooooofu24/sindbad#11]
users/{id} POST (_method=PUT) でメールアドレスを登録した際、登録したアドレス宛に認証メールが届くことを想定していましたが、メールが届きませんでした。

**Comment by tooooofu24** [comment]
すみません、実装漏れです。
確認します。

**Comment by tooooofu24** [comment]
対応しました。 57ef05dbc62ffc81cfe49a6f1b550b29f964f4c2  
ユーザーのメールアドレスの変更をキャッチしてメール送信するように変更しました。
