### ISSUE TITLE
移動手段エレメント　id=8の要素がid=0に変換される？

### ISSUE THREAD

**Issue by tkc-alien** [tooooofu24/sindbad#20]
plans POSTの際、plan_elementsに type=2, id=8 の要素を含めた場合、その後に該当のPlanを取得すると該当エレメントのidが0になっています。

**Comment by tooooofu24** [comment]
対応しました。
このようになっています。
```
1 その他
2 車
3 電車
4 バス
5 飛行機
6 船
7 徒歩
8 自転車
```
